# User config
author: "Oleksii Sidorov"
tagline: "Oleksii Sidorov homepage"
description: "Hi, I'm an AI Resident in Facebook AI Research based in Menlo Park, California"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
